[project]
name = "adventofcode2020"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nixill", email = "github@nixill.net" }
]
requires-python = ">=3.14"
dependencies = [
    "adventofcoderunner",
]

[project.scripts]
adventofcode2020 = "adventofcode2020:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "nixill",
    "adventofcoderunner",
]

[tool.uv.sources]
adventofcoderunner = { workspace = true }
